import { defineConfig } from 'orval';

export default defineConfig({
  petStore: {
    input: {
      // Point directly to the swagger.json file generated by NestJS
      target: '../backend/swagger.json',
    },
    output: {
      target: './src/generated/api.ts',
      schemas: './src/generated/model',
      client: 'axios',
      clean: true,
      mock: false, // Generates MSW mock handlers automatically
      override: {
        mutator: {
          path: './src/libs/apiClient.ts', // Optional: attach auth tokens/interceptors
          name: 'apiClient',
        },
      },
    },
  },
});
